

wx:
  pay:
    #公众号appid
    appId:
    #商户id
    mchId:
    #支付api安全密钥
    mchKey:
    #支付类型
    trade_type: NATIVE
    #支付结果回调地址
    pay_notify:
    #退款结果回调
    refund_notify:
    #证书地址
    keyPath: /keystore/wx_pay_cert.p12
server:
  port: 8011